/**
 * Brain Nutrient API
 * API documentation for Brain Nutrient project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface DummyControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    dummyControllerGenerateBadRequestError(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dummyControllerGenerateInternalServerError(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dummyControllerGenerateNotFoundError(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dummyControllerGenerateTimeoutError(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dummyControllerGenerateUnauthorizedError(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    dummyControllerGenerateValidationError(id: number, extraHttpRequestParams?: any): Observable<{}>;

}
