/**
 * Brain Nutrient API
 * API documentation for Brain Nutrient project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createUserDto 
     */
    userControllerCreateUser(createUserDto: CreateUserDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param email 
     */
    userControllerDeleteUser(email: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param email 
     */
    userControllerGetUserByEmail(email: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param email 
     * @param body 
     */
    userControllerUpdateUser(email: string, body: object, extraHttpRequestParams?: any): Observable<{}>;

}
